### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by illuminati945** [davidlday/RemindersWidget#3] opened 2017-02-21 23:08 UTC
![screen shot 2017-02-22 at 10 06 56 am](https://cloud.githubusercontent.com/assets/20105326/23189405/e11dfeda-f8e6-11e6-91da-ea49445e34b9.png)

What Do i do?

**Comment by davidlday** [comment] 2017-02-22 00:01
Has this worked previously and just now stopped, or is this the first time you've set this up?

Also, can you run a little test for me? Open a terminal, and run the following:

`
sqlite3 $HOME/Library/Calendars/Calendar\ Cache "SELECT name FROM sqlite_master WHERE name IN ('ZICSELEMENT','ZCALENDARITEM')"
`

You should get back either 'ZCALENDARITEM' or 'ZICSELEMENT'. If you get the same error, that'll help me know where to start.

**Comment by illuminati945** [comment] 2017-02-22 00:44
It has never worked.
This is the error:
"Error: unable to open database "/Users/levy": unable to open database file"
I think it might be because my username has two parts two it?

**Comment by davidlday** [comment] 2017-02-22 16:31
Good call - I didn't account for the possibility of spaces in $HOME. I'll have a look this evening, but should be an easy fix.

**Comment by illuminati945** [comment] 2017-02-22 19:37
Sweet, tell me what you come up with

**Comment by davidlday** [comment] 2017-02-23 01:25
I've committed and pushed the fix here. I don't know how long before Ubersicht picks up the change, but you can download reminders.widget.zip from this repo directly and test it out. I'll leave the issue open for now, but if I don't hear back from you by next Monday I'll consider it fixed and close the issue. Best of luck, and thanks for bringing this to my attention!

- D

**Comment by illuminati945** [comment] 2017-02-23 05:58
I downloaded it directly from github, and when i put it in my widgets
folder nothing shows. It is like it was before i ever put the widget in.
well, at least theres no error :)

**Comment by davidlday** [comment] 2017-02-24 02:48
Well, shoot. Okay, let me take a look again this weekend and get back to you.

**Comment by illuminati945** [comment] 2017-02-24 06:53
Alright mate

**Comment by davidlday** [comment] 2017-02-25 14:36
Not having any luck finding anything obvious this time. Once again, can you run the following in the terminal and let me know the output?

`sqlite3 "file:$HOME/Library/Calendars/Calendar Cache?mode=ro" "SELECT name FROM sqlite_master WHERE name IN ('ZICSELEMENT','ZCALENDARITEM')"`

D

**Comment by illuminati945** [comment] 2017-02-26 07:56
"ZCALENDARITEM"

**Comment by davidlday** [comment] 2017-02-26 21:11
Okay - Another one for you to run, pls. This should bring back all tasks:

`sqlite3 "file:$HOME/Library/Calendars/Calendar Cache?mode=ro" "SELECT zduedate,
        zpriority,
        rem.ztitle AS title,
        cal.ztitle AS list,
        rem.znotes AS notes
FROM zcalendaritem rem LEFT JOIN znode cal ON rem.zcalendar=cal.z_pk
WHERE rem.z_ent=6
      AND zcompleteddate IS NULL
      ORDER BY CASE WHEN zduedate IS NULL THEN 1 ELSE 0 END, zduedate, zpriority;"`

**Comment by illuminati945** [comment] 2017-02-27 04:25
"|0|English Due|School Work|"

**Comment by davidlday** [comment] 2017-02-28 00:45
Okay, that's working. One last test, please. 

Can you go to the widgets directory in a terminal and execute:

`cd "$HOME/Library/Application Support/Übersicht/widgets/reminders.widget"`
`./pending.sh`

You should get the same back as json. If that works, then I'm gonna put this on hold to merge in the PR I have open, as the problem may likely lie in the reminders.coffee script.

**Comment by illuminati945** [comment] 2017-02-28 08:12
"

{ "tasks": [ { "dueDate":  " ", "priority":  "0", "title":  "Mrs cook has
my USB. Black, 16gb", "list":  "To Do/Buy", "notes":  " ", "secondsLeft":
" " },{ "dueDate":  " ", "priority":  "0", "title":  "English Due",
"list":  "School Work", "notes":  " ", "secondsLeft":  " " } ], "lists":
["To Do/Buy","Owe others","Owe me","Family","School Work"] }"


Looks like the commands are working, however its still not displaying
anything

**Comment by davidlday** [comment] 2017-03-01 23:52
Can you open the Ubersicht debug console and tell me if you're seeing this: 

`TypeError: undefined is not an object (evaluating 'res.txt')`

or something similar?

**Comment by davidlday** [comment] 2017-03-02 00:16
Okay, I think I have it fixed. Can you try the zip before I push?
[reminders.widget.zip](https://github.com/davidlday/RemindersWidget/files/812388/reminders.widget.zip)

**Comment by illuminati945** [comment] 2017-03-02 03:53
There is nothing in the console, and it still doesnt show anything

**Comment by davidlday** [comment] 2017-03-02 11:36
I was able to recreate the problem (finally) by redeploying the widget several times with Übersicht still running. I think this relates to [Issue 24](https://github.com/felixhageloh/uebersicht/issues/24) of Übersicht, which is still open.

Clear the widget from the cache - the order is important:

1. Shut down Übersicht.
2. Delete `reminders.widget` from Übersicht's widget directory (`$HOME/Library/Application Support/Übersicht/widgets/`)
3. Delete Übersicht's cache directory (`$HOME/Library/Caches/tracesOf.Uebersicht`)
4. Empty trash can.
5. Start Übersicht.
6. Redeploy `reminders.widget` from the zip above.

Let me know if this works.

**Comment by illuminati945** [comment] 2017-03-02 22:24
Still nothing. You reckon it might be a problem with my computer?

**Comment by davidlday** [comment] 2017-03-02 23:18
I have a second person experiencing this problem as well. Let me have them take a run at the fix I offered and see if they have any luck.

I'd hesitate to say there's something wrong with your computer at this point. Do you have other widgets working?

**Comment by illuminati945** [comment] 2017-03-03 00:35
All my other widgets are working perfectly

**Comment by chrisvanklutter** [comment] 2017-03-04 07:35
Hi there, I was finally able to do as you asked me to and delete caches etc. but it still doesn't appear to be working.

**Comment by davidlday** [comment] 2017-03-04 16:49
@illuminati945 and @chrisvanklutter - Thank you both for trying. Let's dig a little deeper. I have a MacBook Air that I haven't installed Ubersicht on yet, so I'm going to try to recreate the problem. Can you both please tell me:

1. OS Version (i.e. I'm at macOS Sierra, Version 10.12.3)
2. Ubersicht Version (Current is 1.0.44)
3. A list of widgets you have installed

I'm going to dig through my system logs on my other machine to see if I can find anything related to when I had this happen there.

- D

**Comment by chrisvanklutter** [comment] 2017-03-04 16:55
1. macOS Sierra, Version 10.12.3 (16D32)
2. Ubersicht Version, 1.1 (45) (Got updated just after I tried to run you widget)
3. Only the reminder wigdet

**Comment by illuminati945** [comment] 2017-03-04 22:03
1. OSX El Capitan, Version 10.11.6
2. Ubersicht Version 1.1 (45)
3. black-bar, SimpleTime, Background, Playbox, reminders (not working),
ToDo (My Widget :)

**Comment by curdaneta** [comment] 2017-03-07 16:09
1. macOS Sierra, Version 10.12.4 Beta (16E175b)
2. Ubersicht Version 1.1 (45)
3. batteryDetails, public_ip, reminders (not working), simple-clock

**Comment by davidlday** [comment] 2017-03-08 23:43
@curdaneta @chrisvanklutter @illuminati945 - I merged in changes from a PR, and made some additional updates to how styling is handled that may fix this issue. I encountered some pretty strange behavior working through this, and externalizing the style sheets seemed to work. Would you each mind testing out the following version before I commit?

[reminders.widget.zip](https://github.com/davidlday/RemindersWidget/files/829281/reminders.widget.zip)

Best,
David

**Comment by davidlday** [comment] 2017-03-08 23:56
@jordikitto - would you mind testing out the zip file above as well and let me know what you think? I hope you don't mind, I left the original style as the default, but changing it to the sidebar style is a one-liner in the reminders.coffee script.

Thanks!
David

**Comment by curdaneta** [comment] 2017-03-09 00:14
@davidlday didn't work for me. Followed the previous steps, quit, clear cache. Also nothing to report on the console

**Comment by illuminati945** [comment] 2017-03-09 01:07
Worked for me! Thank you!

**Comment by chrisvanklutter** [comment] 2017-03-09 16:29
Worked for me as well! Thanks for the quick work

**Comment by curdaneta** [comment] 2017-03-09 16:57
@davidlday looks like I missed something or maybe is my beta OS. I'll try again and post my details

**Comment by davidlday** [comment] 2017-03-09 19:17
@curdaneta - sounds good. let me know if you have any luck.

**Comment by curdaneta** [comment] 2017-03-09 19:48
@davidlday Still not working for me. Tried again without succeed. Also tested running only the Reminders Widget. Looks like could be something related to mac OS 10.12.4 Beta (16E183b)

**Comment by davidlday** [comment] 2017-03-10 00:43
@curdaneta - Sorry to hear. Perhaps take a look in Console, and search for errors related to Ubersicht and/or sparkle. I'm going to push the latest changes, close this out, but feel free to open a new issue just for you and we can continue working through it.

**Closed by davidlday** 2017-03-10 00:43 UTC
Labels: bug

**Comment by jordikitto** [comment] 2017-03-10 08:20
Everything works great for my David, love it. The easy of changing between styles should allow for some other cool custom designs too!

**Comment by jordikitto** [comment] 2017-03-10 08:22
I'm interested in your default design, it is 10px from the top and left? So the widget doesn't sit flush against the screen anywhere, just kind of 'hovers' in the left a bit. What made you choose it to be like that? Also are you still using blur, do you have any issues with it?

**Comment by curdaneta** [comment] 2017-03-10 11:22
@davidlday in my case the problem is that the widget doesn't load the reminders. It works, If I use the sidebar.css It renders the CSS, I'm able to change the CSS and works fine but it doesn't load any Reminders.app data

**Comment by davidlday** [comment] 2017-03-10 11:27
@jordikitto - the choice to hover 10px from top left makes it align with two other widgets, one lower left (quote-of-day kinda thing) and one lower right (a clock). And yes, for now I left blur alone, but I may refine it later. These latest changes focused on getting the style externalized. I plan to refine the style more, and maybe even make it so that the default style really just shows instructions on how to apply one of the styles. Would love to hear more of your thoughts on it.

**Comment by davidlday** [comment] 2017-03-10 11:29
@curdaneta - maybe they've updated the reminders database. Can you run the following, pls:

`sqlite3 "file:$HOME/Library/Calendars/Calendar Cache?mode=ro" "SELECT name FROM sqlite_master WHERE name IN ('ZICSELEMENT','ZCALENDARITEM')"`

**Comment by curdaneta** [comment] 2017-03-10 11:52
@davidlday  where should I run this command, from a Terminal window in the reminders.coffee?

**Comment by davidlday** [comment] 2017-03-12 03:05
@curdaneta - my apologies. Yes, open a Terminal window and run there. Doesn't matter what directory you're in.

**Comment by curdaneta** [comment] 2017-03-12 12:32
@davidlday it returns ZCALENDARITEM

**Comment by davidlday** [comment] 2017-03-12 20:16
@curdaneta - okay. Another one to try. Same deal, just run in Terminal. Directory doesn't matter:

`sqlite3 "file:$HOME/Library/Calendars/Calendar Cache?mode=ro" "SELECT z_ent FROM z_primarykey WHERE z_name = 'Task'"`

Let me know the output, then I'll have one more for you to run. And, I hate to ask, but you do have tasks in at least one Reminders list, correct?

**Comment by curdaneta** [comment] 2017-03-12 23:06
Hi @davidlday the command returns   6

**Comment by davidlday** [comment] 2017-03-14 11:10
Okay - one more to make sure pending.sh is working:

`sqlite3 "file:$HOME/Library/Calendars/Calendar Cache?mode=ro" "SELECT zduedate,
        zpriority AS priority,
        rem.ztitle AS title,
        cal.ztitle AS list,
        rem.znotes AS notes
    FROM ZCALENDARITEM rem LEFT JOIN znode cal ON rem.zcalendar=cal.z_pk
    WHERE rem.z_ent=6
        AND zcompleteddate IS NULL
    ORDER BY CASE WHEN zduedate IS NULL THEN 1 ELSE 0 END, zduedate, zpriority;"`

Again, run in a Terminal and post results. Also, the screenshot shows you're using a modified css, correct? Can you attach a copy of that as well, pls?

**Comment by curdaneta** [comment] 2017-03-14 11:24
Done, please check the images

![custom-css](https://cloud.githubusercontent.com/assets/5185821/23898370/4465b5f0-0887-11e7-942c-a192c7fc5df6.png)
![sqlite3-query](https://cloud.githubusercontent.com/assets/5185821/23898371/446d40a4-0887-11e7-8dd9-7b556cddd5b5.png)

**Comment by davidlday** [comment] 2017-03-14 20:32
@curdaneta Would you mind trying with both the default.css and sidebar.css as well and post screenshots of results. And would you mind attaching the custom CSS as a file (not just a screenshot)? You'll need to zip it up or change the extension to .txt. I adjusted my css to try and match what I see in the screenshot, but not sure I got it entirely.

**Comment by jordikitto** [comment] 2017-03-15 03:40
Not that I'm a pro or anything at this. David seems to have a much better idea of how the .sh file works. I see you've got a lot of stuff running? Have you tried running Ubersicht and the Reminders widget only?

It seems to be only on the 10.12.4 beta that people are experiencing this issue. On 10.12.3 and I have no issues, especially with the sidebar on the right. Was it working before 10.12.4?

I'm guessing Apple has changed how they store/handle the Reminders data.

**Comment by curdaneta** [comment] 2017-03-15 19:23
@jordikitto Yes, it was working perfect before 10.12.4

**Comment by davidlday** [comment] 2017-03-16 01:03
@curdaneta - just wanted to confirm the css was fine as well. I figured it was. One more thing to try before I think we have to contribute it to being on 10.12.4 beta. Can you run this from the Terminal and post results, please:

`cd "$HOME/Library/Application Support/Übersicht/widgets/reminders.widget"`
`./pending.sh`

**Comment by curdaneta** [comment] 2017-03-16 01:33
@davidlday this is the output code

`{ "tasks": [ { "dueDate":  "2017-03-13T18:00:00", "priority":  "0", "title":  "Ajustes web ABRA", "list":  "To Do List", "notes":  " ", "secondsLeft":  "-199911" },{ "dueDate":  "2017-03-16T11:15:00", "priority":  "1", "title":  "Torta Fernando", "list":  "To Do List", "notes":  " ", "secondsLeft":  "34989" },{ "dueDate":  "2017-03-16T12:00:00", "priority":  "1", "title":  "Preparar factura Mastique", "list":  "To Do List", "notes":  " ", "secondsLeft":  "37689" },{ "dueDate":  "2017-03-16T15:45:00", "priority":  "1", "title":  "Cuadrar con Goyo web Incidencias", "list":  "To Do List", "notes":  " ", "secondsLeft":  "51189" },{ "dueDate":  "2017-03-17T10:45:00", "priority":  "1", "title":  "Skype Tania", "list":  "To Do List", "notes":  " ", "secondsLeft":  "119589" } ], "lists": [] }

![screen shot 2017-03-15 at 9 31 58 pm](https://cloud.githubusercontent.com/assets/5185821/23977836/fd476790-09c6-11e7-9380-5d6b7e460814.png)

`

**Comment by davidlday** [comment] 2017-03-16 21:28
@curdaneta & @jordikitto - Interesting. I think I see it now. While the query in pending.sh is pulling the data back correctly, the script isn't populating the "lists" element in the json. I'll have to dig in, but I think we've narrowed this down. CSS is fine, querying the Reminders database looks fine, script isn't constructing the json correctly. I'll dig in over the next day or so.

**Comment by davidlday** [comment] 2017-03-16 21:33
I spoke too soon. @curdaneta - One last command to run. I overlooked this part. It pulls back the list names:

`sqlite3 "file:$HOME/Library/Calendars/Calendar Cache?mode=ro" "SELECT ztitle FROM znode WHERE z_ent=42 AND zistaskcontainer=1"`

Let me know the output. I suspect it'll be empty, and I need to do better at abstracting out those magic numbers (42 & 1).

**Comment by curdaneta** [comment] 2017-03-16 21:48
You were right @davidlday it returns nothing, empty, nada!

**Comment by davidlday** [comment] 2017-03-17 00:31
@curdaneta - Excellent (sorta)! I'll take a look at updating. Will need your help in running some tests.

**Comment by curdaneta** [comment] 2017-03-17 00:46
@davidlday cool, I'll be waiting to run the test

**Comment by davidlday** [comment] 2017-03-17 00:53
Okay - got a fix in, pretty simple change. Can you try the attached version, pls?
[reminders.widget.hotfix.zip](https://github.com/davidlday/RemindersWidget/files/849381/reminders.widget.hotfix.zip)

**Comment by curdaneta** [comment] 2017-03-17 01:13
@davidlday You did it, works like a charm! Thanks for all your support!

![screen shot 2017-03-16 at 9 13 14 pm](https://cloud.githubusercontent.com/assets/5185821/24024913/61d56704-0a8d-11e7-9df9-a58dcaa9b771.png)

**Comment by davidlday** [comment] 2017-03-18 16:28
@curdaneta - You're quite welcome. And thank you for working through the issue with me!
