### ISSUE TITLE
No Widget Displayed

### ISSUE THREAD

**Issue by chrisvanklutter** [davidlday/RemindersWidget#5] opened 2017-03-01 14:41 UTC
Hi!

I've just recently downloaded Ubersicht and later on your widget. The Ubersicht app itselfs seems to work however I can't make your widget visible... I is listed as a widget but there is nothing on my Desktop.

**Comment by davidlday** [comment] 2017-03-01 23:39
Hi! - Thanks for pointing this out. I think this is a duplicate of another open issue. Working on a fix now. I'll have a zip file soon for you to test out.

**Comment by davidlday** [comment] 2017-03-01 23:52
Can you open the Ubersicht debug console and tell me if you're seeing this: 

`TypeError: undefined is not an object (evaluating 'res.txt')`

or something similar?

**Comment by davidlday** [comment] 2017-03-02 00:17
Can you try this version before I push? Should be fixed now.
[reminders.widget.zip](https://github.com/davidlday/RemindersWidget/files/812390/reminders.widget.zip)

**Comment by chrisvanklutter** [comment] 2017-03-02 07:10
Sorry I'm in a different time zone so that's why I didn't answer. 
I checked the debugger there was nothing displayed.
I tried your zip-file but it didn't show up aswell.

**Comment by davidlday** [comment] 2017-03-02 23:22
No worries. I didn't really expect an immediate response :)

Can you do me a favor and try the fix I listed in Issue #3 around clearing Ubersicht's cache? Please be sure to download the version from there.

**Comment by curdaneta** [comment] 2017-03-07 10:44
Hi
Same problem here, stop to work on 10.12.4 Beta (16E175b)
The last release didn't work, also no errors/warnings in the Ubersicht debug console

**Comment by davidlday** [comment] 2017-03-07 12:14
Thanks, @curdaneta - please see #3 for more details and work in progress.

**Comment by davidlday** [comment] 2017-03-07 12:15
At this point, I'm convinced this is a duplicate of #3. Closing out

**Closed by davidlday** 2017-03-07 12:15 UTC
Labels: bug, duplicate
